### ISSUE TITLE
ref and ffi versions: Failed at the ref@1.0.2 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by sdebruin** [ZeroCM/zcm#109]
I was getting the error "Failed at the ref@1.0.2 install script 'node-gyp rebuild'." when running the script install-zcm.sh. 

I ended up identifying a workaround, by modifying package.json within /zcm/build/zcm/js/zcm-*.tgz. By changing the version numbers of ref and ffi to 2.1.0 and 1.3.2, respectively, and modifying install-zcm.sh to use this modified .tgz, the script runs. 

My versions of ubuntu, nodejs, and npm are 16.04, 4.2.6, and 3.5.2, respectively.

**Comment by jbendes** [comment]
Fixed by just reinstalling the dependencies from most recent. Not a good fix but it works for now.
