### ISSUE TITLE
there is no sequence number in the transport frame

### ISSUE THREAD

**Issue by edbek** [ZeroCM/zcm#156]
It is bad that there is no sequence number in the transport frame, as is done in the LCM. In addition, the code for C and C ++ is mixed. that in my subjective view is not good.
The project began as a concept well, but unfortunately it does not go to the side of a quality project.

**Comment by jbendes** [comment]
I am very sorry you feel that way. We are always open to improving the project and are happy to address any and all questions.

1) is it bad that there is no sequence number in the transport frame?
A) what exactly do you mean here by "bad"? We have never seen a use for it give the current API of zcm but are open to adding a sequence number if there is a benefit that isn't immediately apparent.

2) mixed c and c++ code
A) Actually the code base for this project is fairly consistent. There are bindings for zcm in c, c++, Java, python, etc. The core of zcm compiles into a shared library that can be linked against on a Linux system. Core zcm for embedded (nonblocking API) is also strictly c89 compliant for embedded systems that only have that option.

We love that there are people like you who are passionate about making quality open source projects and are always open to improving zcm. Happy to discuss any issues you have with zcm and it's design! Feel free submit more issues here or to hop over to chat in real time with the team at https://gitter.im/ZeroCM/zcm

**Comment by jbendes** [comment]
Did you have anything else of concern here? Otherwise, I'll go ahead and close out this issue next week
