### ISSUE TITLE
Proposal: ZCM packages as Julia modules

### ISSUE THREAD

**Issue by rdeits** [ZeroCM/zcm#167]
I wanted to continue the discussion from #163 in a focused thread, so I've made a new issue. 

My goals in doing this are:

* LCM and ZCM have tried, whenever possible, to have ZCM packages correspond to namespaces or modules in the target language, and I want that to work in Julia as well
* In particular, using Julia modules and the Julia import system means that a user can do `import foo: bar_t` and any types that `foo.bar_t` depends on will automatically be imported
* In addition, hooking into the import mechanism means that there's no possibility of the user creating multiple copies of the same type by `include()`-ing the same file twice in different contexts. 

Some things to know about Julia imports before we begin:

* If Julia type A has a field of type B, then type B *must* be defined before type A
* For `import foo` to work, there must be a file on the `LOAD_PATH` called `foo.jl` (or `foo/src/foo.jl` but we won't be using that), and that file must define `module foo`
* A Julia type may *not* have the same name as its module
* Doing `import foo` first checks if `foo` has already been imported and skips reading the file if it has (it's essentially the same as `#ifndef foo; #define foo; include "foo.jl"; #endif` in C++). 
  * But this mechanism uses the *name* foo, not its full path when checking for duplicates. So we need to ensure that different modules always have different names
* Julia modules can be created dynamically using `@eval`, and types can be retroactively inserted into modules using `@eval`

With that in mind, I have a structure that I think works pretty well. I haven't started implementing the EmitJulia.cpp for it, because I wanted to first make sure that the result was correct before I wrote the generator. The proposal is shown in https://github.com/rdeits/zcm-packages-proposal where the `types` folder contains the compiled ZCM types that I'm suggesting we produce. You can try running `demo.jl` to get an idea of what's possible. 

Basic elements of the proposal:
* each top-level package creates a file `package.jl` and a folder `package/`
* each type is wrapped in an "outer" module whose name is fully qualified. So `foo.bar.t1` will be wrapped in a module `_foo_bar_t1`. 
  * This ensures that Julia's `import` mechanism knows that `foo.bar.t1` and `foo.qux.t1` are different modules. 
  * however, that fully-qualified module actually uses the `@eval` trick to define the ZCM types themselves in the target module (`foo.bar` instead of `_foo_bar_t1`)
* if a type depends on another type from the same module, it just has to import the *outer* module. Multiple imports of the same module are no-ops, so this can be done in any order. That solves the dependency problem between types in the same module.
* sub-packages are generated inside `package.jl` by doing `@eval package module subpackage; end`

Benefits of this approach:
* The user sees a perfectly normal Julia module (including submodules), and does not have to have any idea what horrors went into generating it
* Adding a new type to an existing package is easy because every type in the package is just listed linearly and in any order: https://github.com/rdeits/zcm-packages-proposal/blob/93f8c53726698ae04ddd91df4d1d0159f45f2717/types/foo.jl#L10
* Adding a new sub-package is also easy, because every sub-package is generated with a separate `@eval` statement: https://github.com/rdeits/zcm-packages-proposal/blob/93f8c53726698ae04ddd91df4d1d0159f45f2717/types/foo.jl#L4
* Dependencies within modules, across modules, and between packaged and unpackaged types are all handled entirely by Julia's existing import system

Downsides:
* There's some boilerplate around every compiled type to `@eval` that type into its correct module
* Unpackaged types *must* be put into a module so that they can be `import`ed by other types, but that module can't have the same name as the type itself. I've chosen to put `unpackaged_t` into the `_unpackaged_t` module, so users would do:
  * import _unpackaged_t: unpackaged_t
  * this is similar to the workflow in python, where a user would do:
    * from unpackaged_t import unpackaged_t

**Comment by rdeits** [comment]
And, by the way, @jbendes you were totally right about wanting to use the `@eval foo ...` trick 😉

**Comment by rdeits** [comment]
https://github.com/rdeits/zcm/tree/package-modules now implements the above proposal. With it, we can define the following types:

```
package foo;
struct t1 {
	foo.t2 x;
}

package foo;
struct t2 {
	int64_t x;
}

package foo.bar;
struct t3 {
	foo.t1 x;
	unpackaged_t y;
}

struct unpackaged_t {
	int64_t x;
}
```

and then, in Julia, do:

```julia
julia> import foo

julia> foo.t1()
foo.t1(foo.t2(0))

julia> foo.bar.t3()
foo.bar.t3(foo.t1(foo.t2(0)), _unpackaged_t.unpackaged_t(0))

julia> import _unpackaged_t: unpackaged_t

julia> unpackaged_t()
_unpackaged_t.unpackaged_t(0)
```

**Comment by jbendes** [comment]
Wow awesome work! I'm taking a look at it right now and trying to wrap my head around it.

**Comment by jbendes** [comment]
What is the implication for having a type from one package inside a type in a another package. Ie

```c++
package testpkg1;
struct test1 {
    testpkg2.test2 t;
}

package testpkg2;
struct test2 {
    int a;
}
```

Does something like this work? Not that I've ever tried it nor do I really care to haha

**Comment by rdeits** [comment]
Yup, that should just work :tm: I just added a new `bar.t4` which includes a `foo.t2` as its field in https://github.com/rdeits/zcm/tree/package-modules

**Comment by olsoni** [comment]
I'll take a look at this early this week (hoping tonight) and get back.

**Comment by olsoni** [comment]
Hey @rdeits I read over your code and really like the idea (makes the use in Julia a lot more natural). Take a look at #168 for some review comments.
