### ISSUE TITLE
Zcmtype data-members can have naming collisions with generated function-members

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#178]
This is a particularly nasty undocumented restriction of the member names of zcmtypes. In particular, the potential collisions are language specific and will raise errors at different parts in the compile process (if at all). We should at the very least make zcm-gen fail if it detects a naming collision.

**Comment by jbendes** [comment]
This has been implemented for language keywords, but you're right that we forgot to include function names from zcm too. We should take a look at this again

**Comment by jbendes** [comment]
handled in https://github.com/ZeroCM/zcm/pull/457
