### ISSUE TITLE
Node int64 returns "value out of range" if value you try to set has top bit = 1

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#179]

**Comment by jbendes** [comment]
When exactly does this happen? Is this when setting the top bit in an instantiation of a message? What do you think the behavior should be? Automatically cast to signed? Isn't that a bit weird? It feels like you shouldn't be allowed to set the top bit of a signed integer - that you should have to specify it in signed space

**Comment by jbendes** [comment]
So I've confirmed the behavior @olsoni. If you specify with hex, this works just fine. But if you specify an decimal number larger than the max of the signed int64, then it will error. I think this is correct behavior so I am closing out this issue. Reopen if you disagree and want to continue it
