### ISSUE TITLE
csv-writer not working with the basic example

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#182]
I tried the csv-write using the simple cpp/pub example and apparently it can not load the definitions of the example type. What I did exactly
1. Run `source env` in two terminal sessions
2. ./build/cpp/pub in the examples folder
3. `zcm-csv-writer -u "ipc" -o output.csv` in a different terminal.

The output of the csv-writer is then:
```
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Searching for zcmtypes in your path...
Error extracting /home/m/build/types/examplezcmtypes.jar
Error extracting /home/m/build/java/example.jar
Generating csv from live zcm data. Press ctrl+C to end.
  Wrote 0 events
Cleaning up and quitting
```

It this a bug or am I using it wrong?

**Comment by jbendes** [comment]
Hey @erniejunior, it looks like your classpath might be a little messed up. Are you sure there is a file at this location? `/home/m/build/types/examplezcmtypes.jar` and `/home/m/build/java/example.jar`

**Comment by jbendes** [comment]
I'm going to go ahead and close out this issue. Feel free to reopen it if you're still having an issue
