### ISSUE TITLE
Name collision with zcm python package

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#186]
The python package for ZeroCM is called zcm, which collides with [zcm package at pypi](https://pypi.org/project/zcm/1.0.0/). This is especially confusing since that package also allows publish and subscribe operations with ZeroMQ in the backend! Even if I never intend to use the zcm package from pypi, this means that I can not specify the ZeroCM python packag as a dependency in my setup.py scripts.

**Comment by jbendes** [comment]
Very interesting. Unfortunately this repo doesn't get deployed to pypi so it's hard to hold onto a name for a long time. Do you know how to deploy to pipi? We could deploy a package holder there that just tells people to build from source? Or we could actually deploy zcm if you know how to do that with native libraries.

**Comment by erniejunior** [comment]
Deploying to pypi is quite easy using [setuptools](https://pypi.org/project/setuptools/). Maybe it is possibele to integrate it with your waf build system because both are python based? My understanding of waf is quite poor but I would be willing to set up a python package using setuptools when you give me some hints on how the python interface is currently built.

**Comment by jbendes** [comment]
Take a look at `zcm/python` and you'll see a `zcm.pyx` file. It's a file used by `cython` to generate zcm's python bindings. We run that file through cython to create a c file. Then that c file gets compiled into a shared library. The `wscript` inside `zcm/python` also outlines how that works. Happy to help with the waf stuff if you need.

**Comment by erniejunior** [comment]
OK I do understand line 12 in the waf script but what does [line 18](https://github.com/ZeroCM/zcm/blob/85d31344c106e21027185843aa8279b855757d65/zcm/python/wscript#L18) do exactly?

**Comment by jbendes** [comment]
Line 18 creates a shared library through waf. [The waf book](https://waf.io/book/) is a great resource for figuring out waf syntax.

**Comment by erniejunior** [comment]
OK I wrote a setup.py script that turns the .pyx into a proper python package. Have a look at it [here](https://github.com/erniejunior/zcm/tree/feature/python_packaging). You can install it via:
```bash
pip2 install zcm/python/
pip3 install zcm/python/
```
(use the `--user` flag if you do not want to install it system wide yet and do not want to use sudo). It assumes , that the zcm library is already installed!

I also changed the package name from zcm to zero_cm because of the above mentioned collision. If you prefer a different name (e.g. `zerocm`) I am fine with that too. I changed all the examples to use the new import. What is left to do (and why I did not yet create a pull request) is:
1. Automatically pull the zcm version into the setup.py so we do not need to update it by hand. Or does the python package get its own version number? I do not know hat makes more sense.
2. Integrate the installation with waf. I can give you one line of python code that will install it. It would be great if you could tell me where exactly to place it in the waf script so it gets executed _after_ the zcm library has been installed.

**Comment by jbendes** [comment]
So do we still have to run the `cython` command in isolation? i assume the `pip2 install` and `pip3 install` are actual install commands and should be run with the installation of zcm? As in, with the `./waf install`. Is there any way we can claim `zerocm` on the `pip` registry? Otherwise I would expect we'll lose that someday as well. As for the zcm version, we have access to that as part of the waf build so we can address that when we integrate to waf.

**Comment by erniejunior** [comment]
No you do not need to run cython. Pip will do that for you. The above mentioned shell commands are the only ones needed to run cython and install it on the system. Internally, pip uses the setup.py file to figure out how to install the package ([the cython call is hidden here](https://github.com/erniejunior/zcm/blob/e02d48d144b75a90e2ff28b3cf33ca751804d231/zcm/python/setup.py#L12)).

We **do not need to install this via the shell commands**! Since pip is written in python, its API is easily accessible from within python. So instead of the shell commands, we could do the following somewhere within the waf script:
```python
import pip
pip.main(['install', package, '<relative_path_to_zcm/python>'])
```
Since the cython call depends on the zcm-c library, it should happen *after* that library is installed. I would assume that waf does support some kind of dependencies which would enable this?

Registering the package on pypi account is ridiculously simple. Just run `python setup.py register` und it will guide you through the process which might involve creating a pypi account. See [here](https://python-packaging.readthedocs.io/en/latest/minimal.html#publishing-on-pypi) for more details. After that we can even install the python interface using `pip install zero_cm`.

You mentioned `zerocm` instead of `zero_cm` as the package name in your comment above. Does that mean you prefer `zerocm` as a package name? In that case I would change it in my fork.

**Comment by jbendes** [comment]
Yea it would be great to change it to zerocm for consistency with some of the other languages. As for the compilation of the shared library for python, you're saying that the setup.py file will do it for us? Is there any way to split the compilation of the python library and the installation of that library into two different steps? Waf treats building and installing as two discrete steps. So once that is done, it should be really easy to integrate into waf

**Comment by erniejunior** [comment]
OK I will do the renaming in my branch.

There is a way of splitting up build and installation: `pip wheel zcm/python/` builds a .whl file. Those .whl files are the way to go when you distribute your python packages (read more [here](https://pythonwheels.com/) and [here](https://pypi.org/project/wheel/)). Afterwards the .whl file can be installed using `pip install <whl_file>`. Maye we still need to figure out the exact name of the .whl file being created.

**Comment by erniejunior** [comment]
Looks like this is the way to go:
```bash
pip wheel --wheel-dir=<our_build_dir>/<subdir_for_whl_file> zcm/python
pip install --no-index --find-links=<our_build_dir>/<subdir_for_whl_file> zerocm
```
Then we do not need to figure out the exact filename of the .whl file. Taken from [here](https://wheel.readthedocs.io/en/stable/)

**Comment by jbendes** [comment]
So is there a reason why we should upload the actual package to the pip registry? We don't distribute/support the zcm package any way other than through building this repo, so should we just upload a package with a text file saying to clone and build the repo? That way we can reserve the name `zerocm` but not have to support pushing out updates to the package

**Comment by erniejunior** [comment]
The reason would be to reserve the package name to avoid conflicts. If somebody would try to install the python bindings from pip without first installing the c libraries, this would fail (which is sad). 
Nonetheless I would not install a dummy package with a readme because that can be very confusing for unsuspecting users. I think it is OK if we only reupload the package when there is a new release.

**Comment by jbendes** [comment]
@erniejunior the issue is just that we'd have to upload the shared library for each architecture that we want to support. I'm just not sure how to do that. Happy to help if you know, though. Otherwise, I'd just upload a package that asserts and points users to the zcm github page

**Comment by erniejunior** [comment]
There are other python packages that also just act as a wrapper around a shared library (e.g. the Qt bindings for python). They just require you to install the library by hand (e.g. using the system package manager) before you install the python package.

Right now the installation will just fail if zcm is not installed (probably with a linker error). We could catch this error and print out a hint with a link to this repo. So in the 'default' case where the zcm shared library is installed, the python installation works flawlessly while in the 'fault' case the user is informed on how to fix the issue. What do you think about this?

**Comment by jbendes** [comment]
Ahh I like that option way more. We'd need to do a version check as well as far as I'm aware. Is that possible to do? I'll see if I can get to the pip registration today

**Comment by jbendes** [comment]
I pushed up a copy of your branch [here](https://github.com/ZeroCM/zcm/tree/bld-python_package). Made a few small edits. Also tried running the python register command and got this result:
```
$ python setup.py register
Compiling zerocm.pyx because it changed.
[1/1] Cythonizing zerocm.pyx
running register
running egg_info
creating zerocm.egg-info
writing zerocm.egg-info/PKG-INFO
writing top-level names to zerocm.egg-info/top_level.txt
writing dependency_links to zerocm.egg-info/dependency_links.txt
writing manifest file 'zerocm.egg-info/SOURCES.txt'
file z.py (for module z) not found
file e.py (for module e) not found
file r.py (for module r) not found
file o.py (for module o) not found
file c.py (for module c) not found
file m.py (for module m) not found
reading manifest file 'zerocm.egg-info/SOURCES.txt'
writing manifest file 'zerocm.egg-info/SOURCES.txt'
running check
warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

We need to know who you are, so please choose either:
 1. use your existing login,
 2. register as a new user,
 3. have the server generate a new password for you (and email it to you), or
 4. quit
Your selection [default 1]: 

Username: jbendes
Password: 
Registering zerocm to https://upload.pypi.org/legacy/
Server response (410): Project pre-registration is no longer required or supported, upload your files instead.
```

**Comment by erniejunior** [comment]
Ahhhh looks like we are working on this totally in parallel. Lets have a skype call or something? That would be so much faster.

**Comment by erniejunior** [comment]
I am getting the same error when installing via pip if zcm is not installed yet. The issue is that cython does not find the includes and the zcm library when zcm is not installed. You can help it by doing:
```bash
export CPPFLAGS=-I<zcm_repo_checkout>
export LDFLAGS=-L<zcm_repo_checkout>/build/zcm 
```
So I figured out how to specify pip as a build command in waf but how do I specify a separate install command like `pip install --no-index --find-links=<our_build_dir>/<subdir_for_whl_file> zerocm` as mentioned above?

**Comment by erniejunior** [comment]
I completely redid the python_packaging branch on my side and managed to integrate it with waf. I even pull the version information from waf. Please consider my pull request #209!
