### ISSUE TITLE
Unclear how to build for python3

### ISSUE THREAD

**Issue by ernestum** [ZeroCM/zcm#187]
I see in your recent commit history, that you seem to support python3. But I found not way to enable building it. Should I do this via ./waf configure?

**Comment by jbendes** [comment]
Haha that was quick. Didn't think anyone would notice that for a little bit :). So we're at the point where you can build zcm with your python environment setup for python3 and it should build just fine. Zcm is currently unaware of which python version it's building for (it just assumes python is in your environment). Are you interested in being able to build both python2.7 and python3 in the same zcm `./waf build` command?

**Comment by erniejunior** [comment]
Yes. If I had the option for both that would be awesome. How would I set the python environment explicitly? Using python virtualenvs? Or are there any environment variables I have to export?

**Comment by jbendes** [comment]
I am not actually sure which environment variables are needed. I just set up a python virtual environment. and then built with that. I am not familiar with python at all so I have no idea how to build it for two different environments simultaneously. If you were interested in leading that charge, I am happy to help in whatever way I can.

**Comment by erniejunior** [comment]
For a temporary fix look [here](https://github.com/ZeroCM/zcm/issues/186#issuecomment-389862886)

**Comment by jbendes** [comment]
python 3 is fully supported
