### ISSUE TITLE
python api: segfault if the subscription handle is not stored

### ISSUE THREAD

**Issue by ernestum** [ZeroCM/zcm#188]
If the subscription handle, returned by ZMQ.subscribe is not stored in a variable, the application crashes with a segfault. To reproduce change the following in examples/python/basic_test.py
```
 # set up a subscription on channel "TEST"
-subs = zcm.subscribe("TEST", example_t, handler)
+zcm.subscribe("TEST", example_t, handler)
```
This shuld at least be mentioned somewhere but better it just should not crash at all.

**Comment by jbendes** [comment]
Take a look at https://github.com/ZeroCM/zcm/pull/189 for a fix

**Comment by erniejunior** [comment]
Nice that was fast! I hope you merge the pull request soon.
