### ISSUE TITLE
spy_lite ignores invalid library path

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#193]
If I set the path to the library containing the message definitions to something, that does not exist, the spy_lite just ignores this without any warning or error message leaving me wondering what is wrong with my library when there actually was just a typo in the path.

**Comment by jbendes** [comment]
Yea all the tools could do with a bit more error checking. If you wanted to add in what you think is missing, I'm happy to review and merge fairly quickly. Though I thought that spy lite did some error checking at the beginning. Could be wrong

**Comment by jbendes** [comment]
Fixed in https://github.com/ZeroCM/zcm/pull/196
