### ISSUE TITLE
error: enum constant in boolean context

### ISSUE THREAD

**Issue by sudhanvas** [ZeroCM/zcm#194]
While building master branch on Ubuntu 18.04 with `gcc version 7.3.0`, I see the following error pop out of [here](https://github.com/ZeroCM/zcm/blob/master/zcm/util/threadsafe_queue.hpp#L76). It seems like `pushIfRoom` should return a `bool`; whereas, `ZCM_EAGAIN` is a specific return code.

```
In file included from ../zcm/blocking.cpp:5:0:
../zcm/util/threadsafe_queue.hpp: In instantiation of 'bool ThreadsafeQueue<Element>::pushIfRoom(Args&& ...) [with Args = {long unsig
ned int, const char*, unsigned int&, const unsigned char*&}; Element = Msg]':
../zcm/blocking.cpp:391:86:   required from here
../zcm/util/threadsafe_queue.hpp:76:43: error: enum constant in boolean context [-Werror=int-in-bool-context]
         if (!queue.hasFreeSpace()) return ZCM_EAGAIN;
                                           ^~~~~~~~~~
```

It's partly because all warnings being treated as errors during the build. I also see this for the same reason: 

```
../tools/cpp/spy-lite/MsgDisplay.cpp: In function 'void msg_display(TypeDb&, const TypeMetadata&, void*, const MsgDisplayState&)':
../tools/cpp/spy-lite/MsgDisplay.cpp:213:26: error: 'index' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             strnfmtappend(traversal, TRAVERSAL_BUFSZ, &traversal_used,
             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           "[%d]", index);
                           ~~~~~~~~~~~~~~
```

**Comment by jbendes** [comment]
Did you take a stab at fixing them? Seem like relatively straightforward issues to solve

**Comment by sudhanvas** [comment]
While I was able to fix the above errors, I bumped into the following from the Python bindings:

```
zcm/python/zcm.c: In function 'initzcm':
zcm/python/zcm.c:8543:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     __Pyx_INCREF(((PyObject *)(&PyDict_Type)));
     ^~~~~~~~~~~~
zcm/python/zcm.c:8559:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   __Pyx_INCREF(((PyObject *)(&PyInt_Type)));
   ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Any ideas on what the fix for this might be?

**Comment by jbendes** [comment]
Yea I'm not sure what that one is. It's somehow related to cython and the parsing of the python bindings into c. I'm not sure the exact error or how to get rid of it, but I'd guess the cython page would be a good place to start. They probably already know about it.

**Comment by sudhanvas** [comment]
Is there a way, in `waf`, to disable treating warnings as errors, in the meantime?

**Comment by jbendes** [comment]
Probably? Did you push up your fix to the first two issues? I can play around with it a bit, but I don't want to replicate work you already did!

**Comment by jbendes** [comment]
Yea nevermind i just fixed the first two issues that you mentioned. They were pretty small. The python one is not happening for me. Maybe you have a different python or cython version? What is the result of `cython --version` and `python --version`

**Comment by sudhanvas** [comment]
Cool, thanks! Yeah, I just didn't want to push up incomplete work.

Anyway, I've got `Python 2.7.15rc1` and `Cython version 0.28.3`. Does that help?

**Comment by sudhanvas** [comment]
FYI, I'm building ZCM within Docker with Ubuntu 18.04 as the base image. It turns out that these warnings disappear when building with Ubuntu 16.04. These are the software versions Ubuntu 16.04 is using:

- `gcc version 5.4.0 20160609`
- `Python 2.7.12`
- `Cython version 0.28.3`

It seems like there's a `MAJOR` version difference in GCC and just a `PATCH` version difference in Python.

**Comment by jbendes** [comment]
Hmmm yea so we're definitely on different python, cython, and gcc versions. It is definitely all working on 16.04 (which is the most recent version of ubuntu it's been tested on). I also know it works with the following configuration:
Cython version 0.23.4
Python 2.7.12
gcc 8.1.0

because that's what's currently on my laptop. I can try changing over to your cython version and see if anything changes.

**Comment by jbendes** [comment]
So I was able to replicate your issue. Hopefully will have a suggestion or patch here shortly

**Comment by jbendes** [comment]
okay i just pushed up a branch. Would you mind giving it a shot? Not sure why it fixes it, but seems to work for me!

**Comment by sudhanvas** [comment]
Works for me too!
