### ISSUE TITLE
 Helper functions in transport.h generate compiler warnings (-Wunused-function)

### ISSUE THREAD

**Issue by EvilEli** [ZeroCM/zcm#197]
In order to compile the helper functions of transport.h as static inline C99 or higher must be used.
Probably in transport.h, line 192 there is a typo: Shouldn't it refer to `__STDC_VERSION__`  rather than `__STDC_VERSION`? Or did I miss the definition of `__STDC_VERSION`?

Also when including transport.h from a .cpp file, the `__STDC_VERSION__` macro is not available, since it is compiled with a C++ compiler. Probably it is an option to do something like:
```
/* Only define inline for C99 builds or better */
#if (__STDC_VERSION__ >= 199901L) || (__cplusplus)
#define INLINE inline
#else
# define INLINE
#endif
```
However when INLINE stays undefined the helper functions starting at line 229 will be static only. The compiler will then throw warnings for each compilation unit that includes transport.h but does not use those functions.

I'm not exactly sure if there is a special intention to make those functions static inline.
Wouldn't it be feasible to move the implementation of the helper functions to a dedicated source file.
Then the functions would not be compiled into every compilation unit anymore thus not generate that warnings anymore. However, the inline option would be lost.

**Comment by jbendes** [comment]
So it looks like you're 100% correct in identifying that nonexistent variable. I don't think __STDC_VERSION exists and that should be changed immediately. I like your suggestion about what we can change it to. As for the result of not having `inline` available causing compiler warnings, I'm not quite sure what to do about that. Those helper functions are actually used by core zcm code to access the virtual table in the transport. It was originally written such that every function there would be used by both the `nonblocking.c` api as well as the `blocking.cpp` api. However, it looks like there are two functions that are only used by one of the two apis. `zcm_trans_update` is only relevant in the `nonblocking` API and `zcm_trans_get_mtu` is only relevant in the `blocking` api. We can probably silence those compiler warnings with some cleverly used `(void)` calls, but I'd have to play around with it a bit. Are you running into this issue currently?

**Comment by EvilEli** [comment]
We're only running into the issue because we're using a C++ compiler.
The proposed way to define the INLINE macro would already solve the issue for us.
Since inline is supported when using __cplusplus that should do the job.
