### ISSUE TITLE
How to install the tools without having to configure --use-all?

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#202]
Is there a way to install the tools like zcm-spy-lite without configuring the build with `--use-all`? If not there should be? Maybe add an extra flag for the tools. It is really annoying that I have to install java and nodejs just to use the zcm-spy-lite.

**Comment by jbendes** [comment]
Yea this one's a great idea. What do you think about enabling the build of whatever tools we can? Based on what's "use"d in the build, we can enable tools that only use those dependencies

**Comment by jbendes** [comment]
@erniejunior so I just took a look at the build files in zcm and it seems like this is already the case. All you need is libelf and c/cpp dependencies and you should be able to build a bunch of the java-less tools.
https://github.com/ZeroCM/zcm/blob/master/wscript#L363
https://github.com/ZeroCM/zcm/blob/master/tools/wscript#L5
https://github.com/ZeroCM/zcm/blob/master/tools/cpp/wscript#L10

**Comment by jbendes** [comment]
Let me know if that clears this up for you. Maybe you can add some documentation to the docs/ folder to clear up wherever you were confused and we can get that out to the rest of the community?

**Comment by erniejunior** [comment]
Yes this did definitely help. I just added some notes to the build documentation to make this clear without anybody having to read the wscript files. Feel free to merge my pull request.

**Comment by jbendes** [comment]
Fixed in https://github.com/ZeroCM/zcm/pull/207
