### ISSUE TITLE
Werror=stringop-truncation

### ISSUE THREAD

**Issue by MFlossmann** [ZeroCM/zcm#203]
https://github.com/ZeroCM/zcm/blob/fd8fad1c5620a89950579a6b1986917dcd028cf6/zcm/blocking.cpp#L431

When building in manjaro Linux, I get this error:
```[38/42] Linking build/gen/zcm-gen
../zcm/blocking.cpp: In member function ‘zcm_sub_t* zcm_blocking::subscribe(const string&, zcm_msg_handler_t, void*, bool)’:
../zcm/blocking.cpp:431:12: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 33 equals destination size [-Werror=stringop-truncation]
     strncpy(sub->channel, channel.c_str(), sizeof(sub->channel)/sizeof(sub->channel[0]));
```
gcc version 8.1.1 20180531 (GCC) 

I don't know too much about the internal workings of ZCM, but the 33 seems like an off-by-one error of 32 and I think this is a new thing gcc treats as warning-worthy. I tried
`strncpy(sub->channel, channel.c_str(), sizeof(sub->channel)/sizeof(sub->channel[0]) - 1);` and the build was successful. But as I said: Don't know if this breaks something, so I disabled the count warnings as errors flag for my system.

**Comment by jbendes** [comment]
Yea you are totally fine right. It should be size - 1 as the last argument. And then a manual setting of the last character to the null character. I'll whip a branch tomorrow that fixes this and run it by you

**Comment by jbendes** [comment]
Just pushed up a branch https://github.com/ZeroCM/zcm/tree/core-overflow_bugs
Let me know if that addresses this issue for you

**Comment by MFlossmann** [comment]
Yup, works fine now. Thanks a lot! (I'd recommend a merge with master, though ;)

**Comment by jbendes** [comment]
Fixed in https://github.com/ZeroCM/zcm/pull/204
