### ISSUE TITLE
Receive/Publish threads inherit their names from parent thread

### ISSUE THREAD

**Issue by Duam** [ZeroCM/zcm#211]
Hi there,

I use ZCM for a project in which I utilize multiple threads. While debugging via `htop` and `gdb` and some digging in the ZCM code I noticed that the two threads started in `zcm_blocking_t::sendThreadFunc()` and `zcm_blocking_t::recvThreadFunc()` are not named explicitly, but they inherit their name based on the thread calling these functions. If one doesn't know about this, this is a nightmare to debug and leads to a lot of confusion. 

It is easily fixed by adding a line of code in the beginning of those functions:
`pthread_setname_np(pthread_self(), "ZeroCM_send");` or `"ZeroCM_recv"` respectively.

Sincerely,
Paul

Edit: The same is the case for `zcm_blocking_t::hndlThreadFunc()`.

**Comment by jbendes** [comment]
Yeah it'd be great to solve this. See comments in #212

**Comment by jbendes** [comment]
So the suffix "_np" in function you used pthread_setname_np stands for "non posix". That means that the function isn't available on all posix systems. So unfortunately we'd have to find a way around that. We can either #ifdef guard it somehow if we're able to find a #define that signifies that the function is available, or perhaps there is another way to name a thread?

**Comment by Duam** [comment]
After some googling, there seems to be no straight-forward cross-platform way to name threads. However, according to [drfrogsplat's answer on stackoverflow](https://stackoverflow.com/questions/2369738/how-to-set-the-name-of-a-thread-in-linux-pthreads#7989973) it's possible to do this on a variety of POSIX systems with slighty different interfaces:

> #include <pthread.h>  // or maybe <pthread_np.h> for some OSes
> 
> // Linux
> int pthread_setname_np(pthread_t thread, const char *name);
> 
> // NetBSD: name + arg work like printf(name, arg)
> int pthread_setname_np(pthread_t thread, const char *name, void *arg);
> 
> // FreeBSD & OpenBSD: function name is slightly different, and has no return value
> void pthread_set_name_np(pthread_t tid, const char *name);
> 
> // Mac OS X: must be set from within the thread (can't specify thread ID)
> int pthread_setname_np(const char*);

We could create a macro that wraps the corresponding `pthread_setname_np` function depending on what OS we're operating on. I will play around with some possible solutions in the next days, but ultimately I can test it only on my Linux PC.

**Comment by jbendes** [comment]
That sounds great! Yeah i'm all for making it work on as many systems as possible. And If it's not available, simply not calling it. Check out `platform.hpp`
