### ISSUE TITLE
The Java wrapper incorrectly handles multiple subscriptions on the same channel

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#213]
If I have two different `ZCMSubscriber`s subscribing on the same channel, the callbacks of both of them are called two times for each new arriving message.

This bug is related to #104 and caused by the way subscriptions are forwarded to the zcmjni object [here](https://github.com/ZeroCM/zcm/blob/fb92585a5dd17be29158a1c03ec07cdbbe62c596/zcm/java/zcm/zcm/ZCM.java#L127): The (java) zcm object registers itself as the handler for the subscription and then forwards the new data to the subscriptions it stored on its own.

**Comment by jbendes** [comment]
Yep this is definitely a bug. Looking into how to solve it now. I think it could be as simple as returning the subscription from the JNI subscribe call, and deleting all of the old java book-keeping code

**Comment by jbendes** [comment]
Just pushed up a branch to address this. If you don't mind reviewing it, I'm not 100% on JNI - I just read through some of the docs to try and grasp it since I didn't write this the first time. I'm sure I messed something up (maybe threading or memory related) but not sure. Take a look at https://github.com/ZeroCM/zcm/tree/core-java_overhaul

**Comment by jbendes** [comment]
Okay just ported a bunch more functions from c. Not sure how the threading works in jni world (if it's like node, python, etc where there is only one main thread) so still need to look into that

**Comment by jbendes** [comment]
I think it's good to go. Not positive, but feel like it can't be worse than what it used to be. If anyone has a more rigorous test they'd like to put it through than the pub sub in examples, please do. Addressed in https://github.com/ZeroCM/zcm/pull/214

**Comment by jbendes** [comment]
Handled in #214
