### ISSUE TITLE
ZCM for Julia 1.0

### ISSUE THREAD

**Issue by AndreHat** [ZeroCM/zcm#238]
Hi ZCM developers.

Thank you for the work you put into this, its a really useful tool.
We would like to use ZCM in our latest project, but its written in Julia 1.0. I did a fast port and tested it with your basic_test.jl example, looks as if its working. I also made it into a Julia package. The code can be found [here.](https://github.com/AndreHat/ZCM.jl.git)
I am not proficient enough in Julia to make it a package that can auto install its dependencies or register it as an official package. Can someone please look into this? It would be great if we can add ZCM with Pkg.add("ZCM")

**Comment by olsoni** [comment]
Hi @AndreHat,

Thanks for your work getting ZCM.jl working on v1.0. I'll definitely take a look at the changes you had to make to ZCM.jl to get it to work and see if we can incorporate them (we still have some users on v0.6, so we'll likely need to bake in some backwards compatibility). Scheduling-wise, I'll be out for the next week but will take a look at it as soon as I can.

Regarding making ZCM a proper Julia package; unfortunately, I also do not know how to make a Julia package that will properly do the dependency install & build. This is further complicated by the flexibility of the zcm build (system dependent as well as elective on using various parts of the build). We'll need to do some research into how to bake in such an extensive native build for a Julia package.

**Comment by AndreHat** [comment]
Hi @olsoni 

I worked on some of the other examples, not all of the examples work, but most are usable. I also forked your repository and changed zcm-gen to generate modules compatible with Julia 1.0. Since you said there are still users on Julia 0.6 I guess you would not want to pull, because I dropped Julia 0.6 in favor of Julia 1.0. I just want to let you know this exist in case someone needs it. 
The code can be found [here](https://github.com/AndreHat/zcm)

**Comment by olsoni** [comment]
Sounds great @AndreHat, I should be able to take a look at it this week. What I'll probably do is put in some switches that allow us to build the Julia section of ZCM for either 0.6 or 1.0. I've fetched from your fork and pushed it up as `core-julia_1_0`. Let me know if you make any other changes / improvements and I'll pull them in as well as I'm working on it.

**Comment by olsoni** [comment]
Quick update, on `core-julia_1_0` I have the dependency install, build, and environment path setup working for both v0.6 and v1.0 now. I also believe I have `ZCM.jl` working for both versions of Julia. Final thing (which I'm hoping to look at tomorrow) is to go through your changes to zcm-gen's `EmitJulia.cpp` and double check that it will play nice with both versions.

**Comment by AndreHat** [comment]
Hi @olsoni, thanks for the update.
One thing that I haven't had time for yet is to change the generated types' module structure. The parentmodule() gave me some trouble because it returns the generated module's name instead of Main as in Julia 0.6. You can see the conversation [here](https://discourse.julialang.org/t/usage-of-parentmodule/21625). Using the packaged_type.jl example, what (I guess) needs to happen is that the code generated to _packaged_t.jl and _packaged2_t.jl needs to be made modules that is then imported into test_package.jl and then exported again to the top level namespace so that ZCM.jl can access _packaged_t.jl and _packaged2_t.jl. I will look into it this week. At this time I'm trying the TCP code that @jbendes wrote.

**Comment by olsoni** [comment]
Fixed up the emit code so that it's compatible with both Julia versions. Definitely running into a brick wall with the parentmodule() stuff as described above. I made a quick test that shows the required behavior so we can hopefully find something that works.

**Comment by olsoni** [comment]
I think I'm coming to the conclusion that the Julia zcmtypes require either a global --package-prefix or the julia specific --julia-pkg-prefix to be set in order to function correctly. This is because the zcmtype spec allows types to have dependencies outside their own package as specified in their .zcm files. Allowing this dependency in Julia would require the zcmtype files to forcefully import modules into whatever module imported them, which seems like a pretty bad design. This *sort of* worked in v0.6 (though as I've been investigating, I'm finding that it didn't actually work as well as I had though it was), but in v1.0 the mechanisms that were being used to allow this have changed in ways that prevent us from doing what we used to do. 

I think it's probably just treating this as a little wake-up call to force Julia zcmtypes to always have a package prefix (be it global or julia specific) because it's a much healthier design practice anyway. Note that Java already functions this way -- it defaults the --jpkgprefix option to be 'zcmtypes' if the user does not provide one. My plan moving forward would be to set a default value of the Julia package prefix, identical to how we treat Java.

@jbendes @AndreHat opinions on this? Happy to chat more on gitter.

**Comment by AndreHat** [comment]
@olsoni This sounds like a good idea.

**Comment by olsoni** [comment]
Alright, I implemented the changes suggested above and am not passing all tests within the examples with julia in both versions 0.6 and 1.0. I'm going to move this to a pull request #241

**Comment by olsoni** [comment]
Hey @AndreHat, @jbendes and I have reviewed the pullreq (#241) and are ready to hit merge. Would you mind just double checking that everything's running for you as well?

**Comment by AndreHat** [comment]
Hi @olsoni, looks like it works. I built the examples and encountered no problems. Just one little nitpick. When the example types are built it creates a module called julia.jl that needs to be imported with 'import julia.zcmtypes' in Julia. This might be a bit confusing if you have a big program with 'using julia.zcmtypes' at the top but it includes a zcm module. Maybe change julia to julia_zcm or something a little more descriptive. Its not really a problem, but its the only thing I could see that might be improved, what do you think?

**Comment by olsoni** [comment]
Ah yeah no problem, I was just spit-balling a julia prefix that would have multiple levels just to test that out, but I agree that it's a bit confusing. I'll change it to be `juliazcm.types` for more clarity then merge it.

**Comment by olsoni** [comment]
#241 merged
