### ISSUE TITLE
`inproc` and `ipc` transports do not release their lock files on destruction

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#251]
This can often cause errors like:
```
Failed to acquire publish lock on CHANEL_NAME! Are you attempting multiple publishers?
```
Fortunately commit e91923d fixes the bug. This issue is just to motivate you to merge the pull request :-)

**Comment by jbendes** [comment]
Duplicate of https://github.com/ZeroCM/zcm/issues/50. Closing this issue
