### ISSUE TITLE
Current Travis build is actually failing

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#265]
Thanks for merging the test PR by the way! I just updated my forks master to upstream and for me, the Travis build fails even though it is exactly the same commit hash. [See here for the details](https://travis-ci.org/erniejunior/zcm/builds/558775342).

It fails because apparently zcm-gen is not installed. Maybe it somehow was still in the cache for your build? While rebasing my debian packaging pull request I found out, that you removed zcm-gen from some place of the `wscript` files. Maybe that can be the cause? I am still confused why you Travis build passes.

**Comment by jbendes** [comment]
Looks like your path isn't getting set up properly. Did you change the `.travis.yml` file? This is definitely working on `zcm/master`.

**Comment by jbendes** [comment]
Ahhh nope looks like you're 100% right. Working on a fix. Should be up momentarily

**Comment by jbendes** [comment]
Fixed in https://github.com/ZeroCM/zcm/pull/266

**Comment by erniejunior** [comment]
Awesome thanks!
