### ISSUE TITLE
zcm spy and logger in mixtured transportation

### ISSUE THREAD

**Issue by johnzjq** [ZeroCM/zcm#271]
We are migrating from LCM to ZCM. Some of the messages are sent via IPC while others are sent via UDP multicast. However, the zcm-spy and zcm-logger seem can only be set to monitor either the IPC or the UDPM, which makes the migration meaningless. Is it a limitation of ZCM or what I am doing is not correct? Please help!

**Comment by jbendes** [comment]
Hey @johnzjq, you are correct that each zcm instance only operates on one transport. When you spy or log zcm traffic, you're doing so on only one transport. If you want to spy/log all of your traffic from many different transports with one instance of `zcm-spy` or `zcm-logger`, you can bridge all of the traffic to one transport "subnet" and log there. You'd use `zcm-bridge` to do this. Does this make sense?
