### ISSUE TITLE
data sending from zcm udpn to node

### ISSUE THREAD

**Issue by didibaba** [ZeroCM/zcm#273]
Is is possible to send data from udpm using c++ to node client?

I tried but it didn't work.

Hope for some more detailed explaination.

THX!

**Comment by didibaba** [comment]
I tried 
var z = zcm.create(zcmtypes, "udpm://239.255.76.67:7667ttl=0");
to initialize zcm, but when data recieved I got 
Err: hash mismatch on PacketImage.
Received:
 Integer { value: 8918886700025666805n }
Expected:
 Integer { value: 13998763953574919375n }.

**Comment by jbendes** [comment]
A hash mismatch happens when the schema of the transmitted message doesn't
match the schema of the type used the subscription on the receiving side.
Where are you trying to receive this data? What is your whole setup?

**Comment by didibaba** [comment]
@jbendes I think I find the problem. All the data type .hpp were generated by lcm. It has no problem with cpp progarms but hash mismatching with nodejs ones.

**Comment by jbendes** [comment]
That's interesting. I'm don't think zcm hashes match lcm anymore. Though I
believe there are compile time flags that preserve that backward
compatibility if you want.

**Comment by didibaba** [comment]
Is it correct to use like this ?
```javascript
var zcm = require('zerocm');
var zcmtypes = require('zcmtypes');
var z = zcm.create(zcmtypes, "udpm://239.255.76.67:7667ttl=0");
if (!z) {
    throw "Failed to create ZCM";
}

z.subscribe("A", zcmtypes.PacketA, function(channel, msg) {
    // console.log("Typed message received on channel " + channel);
    console.log(msg);
}, function successCb (_sub) {
});

z.subscribe("B", zcmtypes.PacketB, function(channel, msg) {
    // console.log("Typed message received on channel " + channel);
    console.log(msg);
}, function successCb (_sub) {
});

z.subscribe("C", zcmtypes.PacketC, function(channel, msg) {
    // console.log("Typed message received on channel " + channel);
    console.log(msg);
}, function successCb (_sub) {
});

z.subscribe("D", zcmtypes.PacketD, function(channel, msg) {
    // console.log("Typed message received on channel " + channel);
    console.log(msg);
}, function successCb (_sub) {
});

setInterval(function() {}, 10000);
```
I always got Segmentation fault (core dumped) after receiving several frames. But this would not happen if I only subscribe one channel.

**Comment by jbendes** [comment]
Take a look at the FAQs on the www.zcm-project.org website:
http://zerocm.github.io/zcm/docs/FAQs.html

The last question I believe is the one you're asking.

**Comment by didibaba** [comment]
Thx a lot. This has been solved.

However, another weird thing happened that the interval I receive one mesage is either too large or too small.

For example, I send messages with interval of around 80ms, but the interval between two messages I received  sometimes to be over 1000ms sometimes to be 2ms.

**Comment by jbendes** [comment]
Let's start a new question in the forum if you're still having trouble. And
please provide a code sample or a way to replicate your issue.
