### ISSUE TITLE
Error using zcm nodejs with webpack

### ISSUE THREAD

**Issue by didibaba** [ZeroCM/zcm#284]
First error I got using zcm with webpack is like below:

> ERROR in ./node_modules/engine.io/node_modules/ws/lib/WebSocketServer.js
> Module not found: Error: Can't resolve 'tls' in '/.../node_modules/engine.io/node_modules/ws/lib'
>  @ ./node_modules/engine.io/node_modules/ws/lib/WebSocketServer.js 15:10-24
>  @ ./node_modules/engine.io/node_modules/ws/index.js
>  @ ./node_modules/engine.io/lib/server.js
>  @ ./node_modules/engine.io/lib/engine.io.js
>  @ ./node_modules/socket.io/lib/index.js
>  @ ./modules/custom_server/node_modules/zerocm/index.js
>  @ ./modules/custom_server/src/main.js

After I tried the solution by adding  ` node: {fs: 'empty', net: 'empty', tls: 'empty' }` to the config, the compile is sucessful.

Howerver, when  I use `const zcm = require('zerocm');` in the js file, I will get the error below using webpack.

> */var r=Object.getOwnPropertySymbols,i=Object.prototype.hasOwnProperty,o=Object.prototype.propertyIsEnumerable;function s(e){if(null==e)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}e.exports=function(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de","5"===Object.getOwnPropertyNames(e)[0])return!1;for(var t={},n=0;n<10;n++)t["_"+String.fromCharCode(n)]=n;if("0123456789"!==Object.getOwnPropertyNames(t).map((function(e){return t[e]})).join(""))return!1;var r={};return"abcdefghijklmnopqrst".split("").forEach((function(e){r[e]=e})),"abcdefghijklmnopqrst"===Object.keys(Object.assign({},r)).join("")}catch(e){return!1}}()?Object.assign:function(e,t){for(var n,a,c=s(e),u=1;u<arguments.length;u++){for(var l in n=Object(arguments[u]))i.call(n,l)&&(c[l]=n[l]);if(r){a=r(n);for(var p=0;p<a.length;p++)o.call(n,a[p])&&(c[a[p]]=n[a[p]])}}return c}},func

> TypeError: Cannot read property 'indexOf' of undefined
>     at Function.t.getFileName (/xxx/dist/bundle.js:74:6089)
>     at t (/xxx/dist/bundle.js:74:5248)
>     at Object.<anonymous> (/xxx/dist/bundle.js:14:7391)
>     at Object.<anonymous> (/xxx/dist/bundle.js:26:1206)
>     at n (/xxx/dist/bundle.js:1:110)
>     at Object.<anonymous> (/xxx/dist/bundle.js:69:113977)
>     at n (/xxx/dist/bundle.js:1:110)
>     at Object.<anonymous> (/xxx/dist/bundle.js:69:110370)
>     at n (/xxx/dist/bundle.js:1:110)
>     at Module.<anonymous> (/xxx/dist/bundle.js:67:38195)

Anyone has tried this before?

**Comment by jbendes** [comment]
Can you provide some context as to what it is you're trying to do? Are you able to modify an example inside of `zcm/examples` to break in the way you're seeing?

**Comment by didibaba** [comment]
Actually, this was caused by webpack packing some packages including fs, net and tls.
I have temporarily solved this by consulting https://jlongster.com/Backend-Apps-with-Webpack--Part-I.
