### ISSUE TITLE
compile both python2 and python3 support on the same machine

### ISSUE THREAD

**Issue by BigTailFox** [ZeroCM/zcm#290]
hello,
I use Ubuntu16.04, and need to compile a python3 version zerocm. The default python of system is python2, so I compiled the python2 version zerocm before. However, now my program needs some libraries in python3, but I am not sure how to compile a python3 version zerocm.

**Comment by jbendes** [comment]
It's actually strangely straightforward. You simply type `python3` in front of your waf commands. So for example `python3 ./waf configure` as opposed to `./waf configure`

**Comment by jbendes** [comment]
I also just pushed up a branch to make it work with python3. Give travis a minute to run through the tests and then we'll get it merged

**Comment by jbendes** [comment]
Seems like there's a missing dependency. Will have to take a look tomorrow. You're also welcome to checkout the branch and see if you can fix that. Probably a missing dependency or a wrong path

**Comment by BigTailFox** [comment]
thank you, it works!
Just a few minutes ago before I saw your reply, I tried `./waf configure --use-python --python=/usr/bin/python3`, and take another step to copy the .so from `/usr/local/lib/python3/dist-packages` to `/usr/local/python3.5/dist-packages`. 
I also tried `python3 ./waf configure`, and it works the same.
