### ISSUE TITLE
Can ZeroCM be compiled on Windows?

### ISSUE THREAD

**Issue by BigTailFox** [ZeroCM/zcm#305]
hello,
Since LCM can be built on Windows system, is there any way to compile ZeroCM on Windows? Or any trick to use ZeroCM on Windows?

**Comment by jbendes** [comment]
Zcm can be easily compiled on windows through windows Linux support. You
can install Ubuntu as a lightweight app on windows through the Microsoft
"app store" and then install zcm as normal.

**Comment by BigTailFox** [comment]
Thank you! 
By the way, whether the program compiled in WSL can be used on the native Windows out of WSL?

**Comment by jbendes** [comment]
Unfortunately not right now. It was on the radar for a while, but nobody
was asking for it. What's your use case that needs it? Threading is really
the one thing that requires a posix system at the moment.

Best,
Jonathan

**Comment by BigTailFox** [comment]
I am doing a project for autonomous driving simulation, using ZCM to communicate between the simulation software CARLA and my autonomous driving system. To integrate the CarSim dynamics model the simulation server has to run on Windows. To avoid network spending the simulation client is better to run on the same machine with the server. I am now using LCM instead.
LCM and ZCM are both great projects, Much appreciation!

**Comment by jbendes** [comment]
Makes sense. And thanks for the feedback! Best of luck!
