### ISSUE TITLE
zcm-gen -p tries to write files under /

### ISSUE THREAD

**Issue by tmplt** [ZeroCM/zcm#316]
I'm porting my LCM programs over to ZCM on NixOS and stumbled upon the following:
```
$ cat dwm.lcm
package dwm;

// TODO: refer to DWM documentation
struct position_t
{
        int64_t timestamp; // in milliseconds
        int32_t x;
        int32_t y;
        int32_t z;
        int8_t q;
}
$ zcm-gen -p dwm.lcm
fopen: No such file or directory
An error occurred while emitting Python code.
```
Or more specifically:
```
$ strace zcm-gen -p dwm.lcm
...
stat("/dwm/__init__.py", 0x7ffdbc9addf0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dwm/__init__.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
...
```

Presumbly, `zcm-gen -p` assumes something about the system state that is not true on NixOS.

**Comment by jbendes** [comment]
I think you just need to specify the `--ppath` python path for the destination files. Should definitely be clearer in documentation

**Comment by tmplt** [comment]
`zcm-gen -p --ppath . dwm.lcm` generated the file tree I wanted. Looking at the output of `zcm-gen --help` it seems that the default is... empty? I'm unsure how `[  ]` should be interpreted. Does it then default to `/`? I recommend changing it to `.` to match the behavior of `zcm-gen -c`.

**Comment by jbendes** [comment]
I think that's a great idea! Done and merged to master. https://github.com/ZeroCM/zcm/pull/317
