### ISSUE TITLE
Python3 ImportError: No module named 'zerocm'

### ISSUE THREAD

**Issue by yujmo** [ZeroCM/zcm#319]
When I compiled the dockerfile with the `docker build -t zcm .` command, there was no error.  However, when I execute the `docker build -t zcm .`  command in the python3 environment, the following error occurs:

_[root@vultr zcm]# docker run -it zcm /bin/bash
root@2e2e9cd86541:/# python3
Python 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
**>>> from zerocm import ZCM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'zerocm'**_

Can you tell me how to solve this problem? Thanks.

**Comment by jbendes** [comment]
That's a great question. I see the issue. It's a simple install location
difference. I have no idea why waf is installing the file in the wrong
location but will look into it asap. For now, you can just point your
sys.path at the folder that the python file is being installed to on your
system.

**Comment by yujmo** [comment]
According to your suggestion, I have taken some measures.：
`
[root@vultr zcm]# **_docker run -it zcm /bin/bash_**
root@551aae4971da:/# _**cp /zcm/build/zcm/python/zerocm.cpython-35m-x86_64-linux-gnu.so  /usr/lib//python3/dist-packages
/**_
root@551aae4971da:/# python3
>>> from zerocm import ZCM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libzcm.so: cannot open shared object file: No such file or directory
`

 Now there is a new problem:‘can not find libzcm.so’.  To solve this problem, I copied **_/zcm/build/zcm/libzcm.so_** to **_/usr/lib/python3/dist-packages/_**. But the problem remains unsolved. 😂😂😂

**Comment by jbendes** [comment]
Thankfully that one's much easier. I'm a bit confused though as to how
you're having that problem. Can you walk me through exactly what you're
running? And to fix it, you just add libzcm.so to a directory on your
LD_LIBRARY_PATH

**Comment by yujmo** [comment]
Thank you very much. I have finally solved this problem. 

`root@551aae4971da:/zcm/build/zcm# **_export LD_LIBRARY_PATH=/zcm/build/zcm_**
root@551aae4971da:/zcm/build/zcm# python3
Python 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> **_from zerocm import ZCM_**
`

I pulled the **_zcm repo_** directly from GitHub, and I compiled the Dockerfile using the **_docker build -t zcm ._** command. Then I started a docker container **_docker run -it zcm /bin/bash_**. When I executed **_from zerocm import ZCM_** in the environment of python3, the previous error occurred. 


Finally, I added the following command to **_Dockerfile_**. 
**_RUN echo "export LD_LIBRARY_PATH=/zcm/build/zcm" >> /root/.bashrc && cp /zcm/build/zcm/python/zerocm.cpython-35m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/_**

My previous problems have been completely solved. Thank you very much.

**Comment by jbendes** [comment]
Perfect. I will fix the dockerfile today. Thanks so much for investigating!
