### ISSUE TITLE
python publish_raw truncate message after b'\x00'(if message has this bytes)

### ISSUE THREAD

**Issue by PengKiKi** [ZeroCM/zcm#322]
https://github.com/ZeroCM/zcm/blob/cfa58b5dbaa18ee9de221e6cf960976bbc0fc4f9/zcm/python/zerocm.pyx#L135
I am facing some issues when I try to send a message through publish_raw. The message truncated after the first b'\x00' if I have b'\x00' in my message

I changed this line from 
```python
 return zcm_publish(self.zcm, channel.encode('utf-8'), _data, len(_data) * sizeof(uint8_t))
```
to 
```python
 return zcm_publish(self.zcm, channel.encode('utf-8'), _data, len(data) * sizeof(uint8_t))
```
Then it works

**Comment by jbendes** [comment]
@PengKiKi this is a great catch! Do you want to do a pullreq? Or would you like me to just make the change?

**Comment by jbendes** [comment]
Addressed in https://github.com/ZeroCM/zcm/pull/323
