### ISSUE TITLE
Tools: rename zcm-lspy to be more consistent with other tool naming

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#33]
If this should be deprecated because of the existence of the cpp zcm-spy-lite, we should just delete it, otherwise, we should rename it as something like: zcm-spy-clite so the tab completion on the command line is more consistent. (ie zcm-l"tab" should always go to logging related tools and zcm-s"tab" should always go to spy related tools)

**Comment by jbendes** [comment]
This has been renamed to spy-peek. It's purpose is just to print a small message to the terminal on receipt of a message. Lighter than spy-lite because it needs no shared lib, it only prints the message name.

**Comment by olsoni** [comment]
this wasn't actually changed in the wscript so it was still installing as zcm-spy-peek. This has been updated on master.
