### ISSUE TITLE
Tools: zcm-logger does not read the ZCM_DEFAULT_URL env variable or the "-l" option, it forces you to use the "--zcm-url=" option 

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#34]

**Comment by jbendes** [comment]
This was just incorrect parsing of command line arguments. Fixed on master

**Comment by olsoni** [comment]
Just tested this on master and having the same problem described in the initial issue ... reopening

**Comment by olsoni** [comment]
Additionally, it seems that the --split and --increment don't work properly together for large files (potentially related to 64 bit file size)

**Comment by jbendes** [comment]
The title of this issue is misleading as the correct short opt is "-u" for "--zcm-url" Both of those should work.

**Comment by olsoni** [comment]
haha now it's "-u" after you changed it :) but I agree with the new arg character
