### ISSUE TITLE
spy-lite prefix unexpected behavior

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#355]
2 things, one major, one minor

Major : if you type a prefix and then hit enter, this lets you enter a channel number as expected. However, once you've hit enter, you can't easily exit prefix mode to go back to the "full" view (specifically, escape does not do this). The only way I've found is to start typing another prefix and then hit escape during typing.

Minor : I'd like it if the arrow keys (or specifically the left arrow) functioned in the same way as the escape key

**Comment by jbendes** [comment]
https://github.com/ZeroCM/zcm/pull/356

I don't think we should do the minor one. Just use escape lol

**Comment by jbendes** [comment]
Okay all special characters are treated as escape as of https://github.com/ZeroCM/zcm/pull/358
