### ISSUE TITLE
Add sanitizer flags to prevent ASAN warnings on hash functions

### ISSUE THREAD

**Issue by olsoni** [ZeroCM/zcm#359]
We should add the following tag to functions that perform hashing so that we can suppress asan integer math warnings in the hash functions of types : 

__attribute__((no_sanitize("integer"))) result_type

**Comment by jbendes** [comment]
I think we might be able to do that with this
```
#if defined(__clang__)
```

**Comment by jbendes** [comment]
Can you get the failure to happen in the repo? I can't get it to happen

**Comment by jbendes** [comment]
Can you get the failure to happen in the repo @olsoni? I can't get it to happen

**Comment by jbendes** [comment]
done as of 21d715feb1cbf650cc488cd6321487607f12e779
