### ISSUE TITLE
NodeJS zcm-gen issues

### ISSUE THREAD

**Issue by ajbonkoski** [ZeroCM/zcm#4]
Currently the NodeJS zcm-gen implementation doesn't work correctly for all zcmtypes. In particular, the type hashes for nested types are incorrect.

**Comment by jbendes** [comment]
This is fixed in https://github.com/ZeroCM/zcm/pull/162. Full support for 64 bit numbers, zcmtype consts, and recursive types. Will hopefully be merged next week

**Comment by jbendes** [comment]
Merged in a6eb950c5a7bad0d37f5f30b9fa3f80a6907bc93
