### ISSUE TITLE
UDP unicast transport

### ISSUE THREAD

**Issue by enricop** [ZeroCM/zcm#414]
Hello,
I've modified just a bit the UDP multicast transport to allow unicast communication between two hosts via UDP. This reduces the versatility of the trasnport, however in our use case we prefer to have this kind of communication. 
![image](https://user-images.githubusercontent.com/667557/211826301-499c81d2-f0e4-4367-ad06-b8dc63ca05f4.png)

It would be nice to have the possibility to choose between unicast and multicast through the passed URL at runtime.

thanks for your support,
enrico

**Comment by jbendes** [comment]
This is great! Can you provide an example usage for this? We'll definitely get this merged. This would be a great addition.

**Comment by jbendes** [comment]
@enricop I've pushed up a branch that builds in this functionality a bit more natively. Can you take a look and see if it does the trick for you? I just copied what you did, but I'm not familiar with unicast, so I'm not sure how to use it haha

**Comment by jbendes** [comment]
Okay this is now tested. I will be merging it shortly

**Comment by jbendes** [comment]
So after further testing I don't believe the above code suggestion is correct. I made several more changes on this branch. It's up for pullreq now
