### ISSUE TITLE
segfault in alpine 3.17

### ISSUE THREAD

**Issue by stealthrabbi** [ZeroCM/zcm#428]
I'm trying to use zeromq in alpine 3.17, but I get a segfault on import.
Docker file contains:

```
FROM node:18-alpine3.17 AS builder

RUN apk add --update --no-cache \
        bash \
        g++ \
        ca-certificates \
        lz4-dev \
        musl-dev \
        cyrus-sasl-dev \
        openssl-dev \
        make \
        python3
```

If I create a simple js file that has the following, the program segfaults. I am installing zeromq from my lock file which targers version 5.3.1

```
const zeromq = require('zeromq');
```

**Comment by jbendes** [comment]
I believe this duplicates https://github.com/ZeroCM/zcm/issues/352
Please let me know if I'm wrong by reopening this issue.

**Comment by stealthrabbi** [comment]
My apologies> The segfault I was experiencing was actually from the node zeromq issue.

**Comment by jbendes** [comment]
Let's chat over in that issue then. If you got it working, I'd love to add some documentation to ZCM and close out that other issue!

**Comment by stealthrabbi** [comment]
I am using the node 18 alpine 3.17 base image, which seems pretty different than the problem discussed in #352. But I'll take a look again.
