### ISSUE TITLE
Build with Bazel

### ISSUE THREAD

**Issue by juanmed** [ZeroCM/zcm#439]
Hi,

First thanks for sharing such an interesting alternative to lcm. Reading through the documentation zcm is really attractive. I would like to build zcm with bazel  and wonder whether you have any ideas/comments on where/how to start. 

On my side, will attempt to understand what waf is doing, and attempt to replicate, though I am not familiar.

Thanks

**Comment by jbendes** [comment]
Waf is actually sort of like a lightweight server less bazel. Is there any
reason you want to rewrite the build system? Personally, I wouldn't bother.

**Comment by juanmed** [comment]
Thanks for your answer and time! Well, the reason is that the project I work on is using bazel. I guess your question is not why bazel over waf (I would not be able to answer anyway); this is more a constraint than a decision I have freedom over. That being said, if you have any further comments or know other projects using zcm with bazel I will appreciate you could share.

**Comment by jbendes** [comment]
Hi Juan,

Bazel can build external libraries. My recommendation would be to just
build zcm as an external dependency to your project.

Best,
Jonathan

**Comment by juanmed** [comment]
Thanks
