### ISSUE TITLE
make zcm properly clean up LCK files when its done with them

### ISSUE THREAD

**Issue by tkbrady** [ZeroCM/zcm#50]

**Comment by tmplt** [comment]
Moving over from LCM to ZCM on NixOS and just stumbled upon this error following the documentation (ipc transport). Does the implementation make any assumptions about the system it runs on?

**Comment by jbendes** [comment]
Zcm works on pretty much any system. Down all the way to embedded C. Of course, certain features and transports are only available on certain systems. The blocking API, for example, assumes that you're on a POSIX compliant system. The default lock file directory is `/var/lock/zcm` but you can also override that with the `ZCM_LOCK_DIR` environment variable. I haven't heard of anyone needing to do this though.

**Comment by jbendes** [comment]
I believe this is already handled. Lock files aren't deleted, but they're only valid based on PID
