### ISSUE TITLE
Make documentation on how to use zcm-spy-lite

### ISSUE THREAD

**Issue by jbendes** [ZeroCM/zcm#65]
Include directions on how to compile a .so and give that so to zcm-spy-lite

**Comment by Dissing** [comment]
I'll take a stab at this one. Want it in a separate document or as a section in [tutorial.md](https://github.com/ZeroCM/zcm/blob/master/docs/tutorial.md#spy-lite)?

**Comment by jbendes** [comment]
Inside the tutorial.md is perfect. Was thinking about splitting up that doc
as it's getting fairly long. What did you think when reading through it?

**Comment by roycohen2013** [comment]
The shared library path should be to the specific .so file not the folder as in the tutorial. 
ZCM_SPY_LITE_PATH=<full path to shared library folder>

**Comment by Dissing** [comment]
Its pretty good but the tools section should probably be in a separate document. One good addition would be a Common pitfalls section documenting things like [this](https://github.com/ZeroCM/zcm/blob/master/zcm/blocking.cpp#L417). Also quite a few of the examples has semicolon after the struct, which makes zcm-gen complain. Is this an error in zcm-gen or just in the tutorial?

**Comment by jbendes** [comment]
That's an error in the tutorial although zcmgen should probably be modified
to handle that. Are you working on the docs? Definitely down to split out
the tools material into a second doc. Also, yes that XXX should definitely
make it into higher level docs haha.

**Comment by Dissing** [comment]
I am currently working inside my own fork. Might as well get all the work into one pull request. I have fixed the issues mentioned, split out the tools section and started to expand it a bit.
